apiVersion: v1
kind: Secret
metadata:
  name: pipeline-secret
  namespace: default
stringData:
  det_master: 10.10.160.170:8081
  det_user: determined
  det_password: ""
  pac_token: ""
  sel_url: http://10.10.160.173
  sel_secret: "12341234"
  sel_namespace: seldon
